### ISSUE TITLE
Dashboard View content

### ISSUE THREAD

**Issue by Laura-Waters** [bluethreadmade/job-app-tracker#61]
- [x] #70
- [x] #71
- [x] #72
- [x] #73
- [x] #101
- [x] #123
- [x] #124
- [x] #126
- [x] #158

**Comment by Laura-Waters** [comment]
## Tasks 

- [ ] Applications Submitted Card
- [ ] Interviews Scheduled Card 
- [ ] Offers Received Card 
- [ ] Current Job Applications Card
